name: omniscribe

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/omniscribe
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/web/:/app/web/
    ports:
      - "5173:5173"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=omniscribe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: